configfile: "config/config.yml"
containerized: config["pipeline_container"]
include: "rules/common.smk"

assembly_name = config["assembly_name"]
assembly_version = config["assembly_version"]

include: "rules/genome_assembly.smk"
include: "rules/organelle_annotation.smk"
include: "rules/softmask.smk"
include: "rules/gene_prediction.smk"
include: "rules/circos_plot.smk"

rule all:
    input:
        *circos_plot_all_inputs(assembly_name, assembly_version),
        *organelle_submission_all_inputs(assembly_name, assembly_version)

rule assembly_all:
    input:
        *assembly_all_inputs(assembly_name)

rule remove_organelle_all:
    input:
        *remove_organelle_all_inputs(assembly_name)

rule remove_contamination_all:
    input:
        *remove_contamination_all_inputs(assembly_name)

rule scaffold_all:
    input:
        *scaffold_all_inputs(assembly_name)

rule softmask_all:
    input:
        *softmask_all_inputs(assembly_name)

rule gene_prediction_all:
    input:
        *gene_prediction_all_inputs(assembly_name, assembly_version)

rule circos_plot_all:
    input:
        *circos_plot_all_inputs(assembly_name, assembly_version)

rule organelle_annotation_all:
    input:
        *organelle_annotation_all_inputs(assembly_name)

rule organelle_visualization_all:
    input:
        *organelle_visualization_all_inputs(assembly_name)

rule organelle_submission_all:
    input:
        *organelle_submission_all_inputs(assembly_name, assembly_version)
