# containerized: "docker://aurelia01/XXX:YYY"
configfile: "config/config.yml"
include: "rules/genome_assembly.smk"
include: "rules/softmask.smk"
include: "rules/gene_prediction.smk"

import os
import glob
sample = glob.glob("raw_data/*.hifi_reads.bam")
if len(sample) == 0:
    raise RuntimeError("No HiFi read files matching 'raw_data/*.hifi_reads.bam' were found. Please check the input directory.")
elif len(sample) > 1:
    raise RuntimeError("Multiple HiFi read files found. Please ensure only one HiFi read file is present in 'raw_data/'.")
sample_id = os.path.basename(sample[0]).replace(".hifi_reads.bam", "")

rule all:
    input:
        f"results/isoforms/{sample_id}_aa.fa",
        f"results/longest_cds/{sample_id}_aa.fa"
