usage:
  software-stack-deployment:
    apptainer+conda: true # whether pipeline works with "--sdm conda apptainer"
  report: true # whether creation of reports using "snakemake --report report.zip" is supported