import json
import shutil
from pathlib import Path


GENBANK_SUFFIXES = (".gb", ".gbk", ".gbf")
FEATURE_INDENT = "     "
QUALIFIER_INDENT = "                     "


def organism_name_from_assembly_name(assembly_name: str):
    organism_name = " ".join(assembly_name.replace("_", " ").split())
    if not organism_name:
        raise ValueError("Assembly name must not be empty when deriving organism name.")
    if any(character in organism_name for character in '"\r\n'):
        raise ValueError(
            f"Assembly name cannot be used as a GenBank organism: {assembly_name!r}"
        )
    return organism_name


def copy_first_genbank(output_dir: Path, annotation_path: Path):
    candidates = sorted(
        path
        for path in output_dir.rglob("*")
        if path.is_file() and path.suffix.lower() in GENBANK_SUFFIXES
    )
    if not candidates:
        raise RuntimeError(f"No GenBank output was found under {output_dir}.")

    annotation_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(candidates[0], annotation_path)
    return candidates[0]


def curate_source_organism(path: Path, assembly_name: str):
    organism_name = organism_name_from_assembly_name(assembly_name)
    organism_line = f'{QUALIFIER_INDENT}/organism="{organism_name}"\n'
    lines = path.read_text().splitlines(keepends=True)

    source_index = None
    for index, line in enumerate(lines):
        if line.startswith(f"{FEATURE_INDENT}source"):
            source_index = index
            break
    if source_index is None:
        raise ValueError(f"No source feature was found in {path}.")

    next_feature_index = len(lines)
    for index in range(source_index + 1, len(lines)):
        line = lines[index]
        if line.startswith(FEATURE_INDENT) and not line.startswith(QUALIFIER_INDENT):
            next_feature_index = index
            break

    previous_organism = None
    organism_index = None
    for index in range(source_index + 1, next_feature_index):
        stripped = lines[index].strip()
        if stripped.startswith("/organism="):
            organism_index = index
            previous_organism = stripped.removeprefix("/organism=").strip('"')
            break

    if organism_index is None:
        lines.insert(source_index + 1, organism_line)
    elif lines[organism_index] != organism_line:
        lines[organism_index] = organism_line

    changed = previous_organism != organism_name
    if changed:
        path.write_text("".join(lines))

    return {
        "source_organism_before": previous_organism,
        "source_organism_after": organism_name,
        "source_organism_changed": changed,
    }


def format_manual_modification_record(post_curation):
    lines = [
        "# Automatic post-curation",
        "",
        "This file is regenerated by the workflow. Add manual notes after the "
        "workflow finishes if you edit the GenBank file by hand.",
        "",
    ]

    source_organism = post_curation.get("source_organism")
    if source_organism:
        before = source_organism["source_organism_before"]
        after = source_organism["source_organism_after"]
        if before is None:
            lines.append(f'- source /organism: added "{after}"')
        elif source_organism["source_organism_changed"]:
            lines.append(f'- source /organism: changed from "{before}" to "{after}"')
        else:
            lines.append(f'- source /organism: already "{after}"')

    lines.extend(
        [
            "",
            "# Manual post-curation notes",
            "",
        ]
    )
    return "\n".join(lines)


def write_manual_modification_record(path: Path, post_curation):
    updated = format_manual_modification_record(post_curation)

    path.parent.mkdir(parents=True, exist_ok=True)
    changed = (not path.exists()) or path.read_text() != updated
    if changed:
        path.write_text(updated)

    return {
        "manual_modification_record": str(path),
        "manual_modification_record_changed": changed,
    }


def write_run_manifest(path: Path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")
